//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIY_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasker()
        {
            this.TaskerComment = new HashSet<TaskerComment>();
            this.TaskerService = new HashSet<TaskerService>();
        }
    
        public int TaskerID { get; set; }
        public string TaskerName { get; set; }
        public short ServiceQuote { get; set; }
        public string TaskerTel { get; set; }
        public string TaskerPhone { get; set; }
        public System.TimeSpan ServiceTime_Start { get; set; }
        public System.TimeSpan ServiceTime_End { get; set; }
        public string ServiceArea { get; set; }
        public string TaskerImage { get; set; }
        public string License { get; set; }
        public string Feature { get; set; }
        public string TaskerDescription { get; set; }
        public string CaseImage { get; set; }
        public Nullable<decimal> Rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskerComment> TaskerComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskerService> TaskerService { get; set; }
    }
}
